- name: Create Homework Assignment project
  tower_project:
      name: "{{ proj_name }}"
      scm_branch: "{{ scm_branch }}"
      tower_password: "{{ password }}"
      tower_host: tower1.{{tower_GUID}}.example.opentlc.com
#      scm_credential: undefined # not required. Name of the credential to use with this SCM resource.
      scm_clean: no # not required. Remove local modifications before updating.
      scm_url: "{{ scm_url }}"
      scm_delete_on_update: no # not required. Remove the repository completely before updating.
#      tower_config_file: undefined # not required. Path to the Tower config file. See notes.
      state: present # not required. choices: present;absent. Desired state of the resource.
#      local_path: undefined # not required. The server playbook directory for manual projects.
      scm_type: git
      scm_update_on_launch: no # not required. Before an update to the local repository before launching a job with this project.
      tower_username: "{{ user_name }}"
      organization: "{{ org_name }}"
      tower_verify_ssl: no 
      description: "{{ proj_name }}"

- name: Machine Credentail to connect to workstation using openstack.pub
  tower_credential:
    name: Connect_to_workstation
    organization: Default
    state: present
    kind: ssh
    tower_host: tower1.{{tower_GUID}}.example.opentlc.com
    tower_username: "{{ user_name }}"
    tower_password: "{{ password }}"
    ssh_key_data: "{{ user_cred_path }}"
    username: cloud-user

- name: Create Inventory
  command: |
    tower-cli inventory create -n "{{static_inventory_name}}" --organization "{{org_name}}"

- name: Create Group in static inventory 
  command: |
    tower-cli group create --inventory "{{static_inventory_name}}"  --name {{group_name}}

- name: Add tower host
  tower_host:
    name: "{{host_name}}"
    description: "workstation"
    inventory: "{{static_inventory_name}}"
    state: present
    tower_host: tower1.{{tower_GUID}}.example.opentlc.com
    tower_username: "{{ user_name }}"
    tower_password: "{{ password }}"
    tower_verify_ssl: no

- name: Associate workstation host to group 
  command: | 
    tower-cli host associate --host "{{host_name}}" --group "{{group_name}}"

- name: Tower Creds key file
  tower_credential:
    name: "{{ opentlc_cred_name }}"
    organization: Default
    state: present
    kind: ssh
    tower_host: tower1.{{tower_GUID}}.example.opentlc.com
    tower_username: "{{ user_name }}"
    tower_password: "{{ password }}"
    tower_verify_ssl: no
    ssh_key_data: "{{ path_to_opentlc_key }}"
    username: "{{ opentlc_login }}"

- name: Remove secret
  file:
    name: /root/secret.pem
    state: absent

